name: Build Release ZIP

on:
  push:
    branches: [ main, master ]
  workflow_dispatch:

jobs:
  build-zip:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Create ZIP package
      run: |
        # 创建临时目录
        mkdir -p temp_package
        
        # 定义排除的文件和目录
        EXCLUDE_PATTERNS=(
          ".git"
          ".github"
          ".gitignore"
          ".gitattributes"
          "README.md"
          ".DS_Store"
          "LICENSE"
          "install.sh"
          "*.log"
          ".env*"
          "temp_package"
          "*.zip"
        )
        
        # 构建rsync排除参数
        EXCLUDE_ARGS=""
        for pattern in "${EXCLUDE_PATTERNS[@]}"; do
          EXCLUDE_ARGS="$EXCLUDE_ARGS --exclude=$pattern"
        done
        
        # 使用rsync复制所有文件，排除指定的文件和目录
        rsync -av $EXCLUDE_ARGS ./ temp_package/
        
        # 创建ZIP文件
        zip -r context-engineering-for-swift.zip temp_package/
        
        # 清理临时目录
        rm -rf temp_package/
        
    - name: Upload ZIP artifact
      uses: actions/upload-artifact@v4
      with:
        name: context-engineering-for-swift
        path: context-engineering-for-swift.zip
        retention-days: 30
        
    - name: Create Release
      if: github.event_name == 'push'
      uses: softprops/action-gh-release@v1
      with:
        files: context-engineering-for-swift.zip
        tag_name: v${{ github.run_number }}
        name: Release v${{ github.run_number }}
        body: |
          ## 自动构建的ZIP包
          
          包含项目的所有必要文件，排除了以下内容：
          - .git 目录
          - .github 工作流目录
          - node_modules
          - .DS_Store 文件
          - 日志文件 (*.log)
          - 环境变量文件 (.env*)
          - 临时文件和构建产物
          
          构建时间: ${{ github.event.head_commit.timestamp }}
        draft: false
        prerelease: false
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
